### ISSUE TITLE
Why do you still use Guavas eventbus for application-internal events?

### ISSUE THREAD

**Issue by jbellmann** [bringmeister/ddd-with-kotlin#1]
Hi,
stumbled about [your bog posts](https://tuhrig.de/ddd-with-kotlin/) and [this one](https://tuhrig.de/encapsulated-modules-with-springs-configuration/) and came to this repo. Had a look into it and found  a configuration for the eventbus provided by guava library. Also used it years ago for application-internal events. But that's not needed anymore. Spring has it's own `eventbus` since years now and also provide an annotation based model (and I guess that's what you maybe liked on guavas, right?).
Have a look to the [well documented feature](https://docs.spring.io/spring/docs/5.0.7.RELEASE/spring-framework-reference/core.html#context-functionality-events-annotation). And yes, also [async event handling](https://docs.spring.io/spring/docs/5.0.7.RELEASE/spring-framework-reference/core.html#context-functionality-events-async) is supported. There is no need for guava dependency anymore ( 2.7 MB in size btw. ). At least not for application internal event handling. ;-)

Happy Coding

**Comment by tuhrig** [comment]
Hey Jörg,

thank you for your feedback! 

We evaluated both, Spring Application Events and Guava, when we wrote this demo. The support for async events was better in Guava in our opinion. We didn't want to have two annotations on each listener:

```
@EventListener
@Async
public void listen(...) {
    ...
}
```

However, I invested some more time and stumbled over [this](http://zoltanaltfatter.com/2016/05/11/application-events-with-spring) blog post. It describes an approach to enable async Spring events without annotating all listeners with `@Async`. With this, it's fine for me to remove Guava. As you said, it's one dependency less.

I already updated the code.

Thanks again and best regards,
Thomas

**Comment by jbellmann** [comment]
Hi Thomas,

great to see you liked the idea of removing Guava for handling events.
Regarding your commment:

> We didn't want to have two annotations on each listener

That's something I understand and fully agree on. The drawback of the solution from the blog you mentioned above is that **all** events are now handled asynchronously (noted in the blog, too). I also found the link in the blog post that mentioned a solution for this (having both, sync and async events). But that solution comes with some more configuration overhead that is not really necessary I think.

My proposal would be to use [Meta-Annotations](https://docs.spring.io/spring/docs/5.0.7.RELEASE/spring-framework-reference/core.html#beans-meta-annotations) instead. Create your own annotation for that, like this one:

```
@Target({ ElementType.METHOD, ElementType.ANNOTATION_TYPE })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@EventListener
@Async
public @interface AsyncEventListener {

    @AliasFor(annotation = EventListener.class, attribute = "value")
    Class<?>[] value() default {};

    @AliasFor(annotation = EventListener.class, attribute = "classes")
    Class<?>[] classes() default {};

    @AliasFor(annotation = EventListener.class, attribute = "condition")
    String condition() default "";
}
```

The benefit would be you can drop the [special configuration class](https://github.com/bringmeister/ddd-with-kotlin/blob/master/src/main/kotlin/de/bringmeister/connect/product/infrastructure/spring/SpringApplicationEventConfig.kt) and the much more useful benefit would be you could control the behaviour (sync/async) on the listeners side. What makes it much more flexible for you.

Try it.
Have fun.
Happy coding.

Jörg
