### ISSUE TITLE
Use Meta-Annotation to combine multiple annotations.

### ISSUE THREAD

**Issue by jbellmann** [bringmeister/ddd-with-kotlin#3]
Hi Thomas,

great to see you liked the idea of removing Guava for handling events.
Regarding your commment:

> We didn't want to have two annotations on each listener

That's something I understand and fully agree on. The drawback of the solution from the blog you mentioned above is that **all** events are now handled asynchronously (noted in the blog, too). I also found the link in the blog post that mentioned a solution for this (having both, sync and async events). But that solution comes with some more configuration overhead that is not really necessary I think.

My proposal would be to use [Meta-Annotations](https://docs.spring.io/spring/docs/5.0.7.RELEASE/spring-framework-reference/core.html#beans-meta-annotations) instead. Create your own annotation for that, like this one:

```
@Target({ ElementType.METHOD, ElementType.ANNOTATION_TYPE })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@EventListener
@Async
public @interface AsyncEventListener {

    @AliasFor(annotation = EventListener.class, attribute = "value")
    Class<?>[] value() default {};

    @AliasFor(annotation = EventListener.class, attribute = "classes")
    Class<?>[] classes() default {};

    @AliasFor(annotation = EventListener.class, attribute = "condition")
    String condition() default "";
}
```

The benefit would be you can drop the [special configuration class](https://github.com/bringmeister/ddd-with-kotlin/blob/master/src/main/kotlin/de/bringmeister/connect/product/infrastructure/spring/SpringApplicationEventConfig.kt) and the much more useful benefit would be you could control the behaviour (sync/async) on the listeners side. What makes it much more flexible for you.

Try it.
Have fun.
Happy coding.

Jörg

**Comment by tuhrig** [comment]
Hi Jörg,

this was my first idea, too. It would also have the benefit to distinguish between event and command listeners (which we also have) and to avoid a direct dependency to Spring in each listener (which is only partly true, because each listener must be a Spring Bean).

My approach looked like this:

```
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.RUNTIME)
@EventListener
@Async
annotation class CommandListener
```

```
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.RUNTIME)
@EventListener
@Async
annotation class EventListener
```

Unfortunately, `@Async` doesn't work when applied on a meta annotation.

**Comment by tuhrig** [comment]
I pushed my version to a branch: https://github.com/bringmeister/ddd-with-kotlin/tree/listener-meta-annotation

But as I said, it's not working.

**Comment by jbellmann** [comment]
Hmm, I will have a look.

**Comment by tuhrig** [comment]
Thanks for your support. I merged your PR.
